resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.sample.app.JaxrsApplication
server:
  port: 9090
  ssl:
    key-store: classpath:selfsigned.jks
    key-store-password: changeme