resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.sample.app.JaxrsApplication
server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: classpath:selfsigned.jks
    key-store-password: changeme
